"""Add store_id column to stores table

Revision ID: 941297f52851
Revises: 
Create Date: 2024-06-13 08:40:15.461607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941297f52851'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_store_id', table_name='store')
    op.drop_table('store')
    op.drop_index('ix_providers_company', table_name='providers')
    op.drop_index('ix_providers_description', table_name='providers')
    op.drop_index('ix_providers_name', table_name='providers')
    op.drop_index('ix_providers_provider_id', table_name='providers')
    op.drop_table('providers')
    op.drop_index('ix_credentials_credential_id', table_name='credentials')
    op.drop_index('ix_credentials_provider_id', table_name='credentials')
    op.drop_index('ix_credentials_user_id', table_name='credentials')
    op.drop_table('credentials')
    op.drop_index('ix_chain_chain_id', table_name='chain')
    op.drop_table('chain')
    op.drop_index('ix_inquiry_content', table_name='inquiry')
    op.drop_index('ix_inquiry_id', table_name='inquiry')
    op.drop_index('ix_inquiry_inquiry_type', table_name='inquiry')
    op.drop_index('ix_inquiry_title', table_name='inquiry')
    op.drop_table('inquiry')
    op.drop_index('ix_stores_id', table_name='stores')
    op.drop_index('ix_stores_user_id', table_name='stores')
    op.drop_table('stores')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_user_id', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_agent_agent_id', table_name='agent')
    op.drop_index('ix_agent_user_id', table_name='agent')
    op.drop_table('agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('agent_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('agent_type', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('is_visible_in_marketplace', sa.BOOLEAN(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updater_id', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_index('ix_agent_user_id', 'agent', ['user_id'], unique=False)
    op.create_index('ix_agent_agent_id', 'agent', ['agent_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updater_id', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_index('ix_user_user_id', 'user', ['user_id'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('store_name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('creator_id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updater_id', sa.CHAR(length=32), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stores_user_id', 'stores', ['user_id'], unique=False)
    op.create_index('ix_stores_id', 'stores', ['id'], unique=False)
    op.create_table('inquiry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('inquiry_type', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('response_content', sa.VARCHAR(), nullable=True),
    sa.Column('processing_type', sa.VARCHAR(), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updater_id', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inquiry_title', 'inquiry', ['title'], unique=False)
    op.create_index('ix_inquiry_inquiry_type', 'inquiry', ['inquiry_type'], unique=False)
    op.create_index('ix_inquiry_id', 'inquiry', ['id'], unique=False)
    op.create_index('ix_inquiry_content', 'inquiry', ['content'], unique=False)
    op.create_table('chain',
    sa.Column('chain_id', sa.INTEGER(), nullable=False),
    sa.Column('agent_id', sa.INTEGER(), nullable=False),
    sa.Column('provider_id', sa.INTEGER(), nullable=False),
    sa.Column('connection_order', sa.INTEGER(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updater_id', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('chain_id')
    )
    op.create_index('ix_chain_chain_id', 'chain', ['chain_id'], unique=False)
    op.create_table('credentials',
    sa.Column('credential_id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('provider_id', sa.CHAR(length=32), nullable=False),
    sa.Column('credential_name', sa.VARCHAR(), nullable=False),
    sa.Column('access_key', sa.VARCHAR(), nullable=True),
    sa.Column('secret_key', sa.VARCHAR(), nullable=True),
    sa.Column('session_key', sa.VARCHAR(), nullable=True),
    sa.Column('access_token', sa.VARCHAR(), nullable=True),
    sa.Column('api_key', sa.VARCHAR(), nullable=True),
    sa.Column('api_endpoint', sa.VARCHAR(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('creator_id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updater_id', sa.CHAR(length=32), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('credential_id')
    )
    op.create_index('ix_credentials_user_id', 'credentials', ['user_id'], unique=False)
    op.create_index('ix_credentials_provider_id', 'credentials', ['provider_id'], unique=False)
    op.create_index('ix_credentials_credential_id', 'credentials', ['credential_id'], unique=False)
    op.create_table('providers',
    sa.Column('provider_id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('company', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('logo', sa.VARCHAR(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('sort_order', sa.INTEGER(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('creator_id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updater_id', sa.CHAR(length=32), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_index('ix_providers_provider_id', 'providers', ['provider_id'], unique=False)
    op.create_index('ix_providers_name', 'providers', ['name'], unique=False)
    op.create_index('ix_providers_description', 'providers', ['description'], unique=False)
    op.create_index('ix_providers_company', 'providers', ['company'], unique=False)
    op.create_table('store',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('store_name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updater_id', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_store_id', 'store', ['id'], unique=False)
    # ### end Alembic commands ###
