"""edit agent table

Revision ID: afa27bafcb30
Revises: a7cf31c3b454
Create Date: 2024-07-10 13:01:32.876359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'afa27bafcb30'
down_revision: Union[str, None] = 'a7cf31c3b454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chain_chain_id', table_name='chain')
    op.drop_table('chain')
    op.drop_index('ix_inquiry_content', table_name='inquiry')
    op.drop_index('ix_inquiry_id', table_name='inquiry')
    op.drop_index('ix_inquiry_inquiry_type', table_name='inquiry')
    op.drop_index('ix_inquiry_title', table_name='inquiry')
    op.drop_table('inquiry')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_user_id', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_credentials_credential_id', table_name='credentials')
    op.drop_index('ix_credentials_provider_id', table_name='credentials')
    op.drop_index('ix_credentials_user_id', table_name='credentials')
    op.drop_table('credentials')
    op.drop_index('ix_agents_agent_id', table_name='agents')
    op.drop_index('ix_agents_fm_model_id', table_name='agents')
    op.drop_index('ix_agents_fm_provider_id', table_name='agents')
    op.drop_index('ix_agents_user_id', table_name='agents')
    op.drop_table('agents')
    op.drop_index('ix_models_model_id', table_name='models')
    op.drop_index('ix_models_model_name', table_name='models')
    op.drop_index('ix_models_model_type', table_name='models')
    op.drop_index('ix_models_provider_id', table_name='models')
    op.drop_table('models')
    op.drop_index('ix_processing_processing_id', table_name='processing')
    op.drop_index('ix_processing_user_id', table_name='processing')
    op.drop_table('processing')
    op.drop_index('ix_store_store_id', table_name='store')
    op.drop_index('ix_store_user_id', table_name='store')
    op.drop_table('store')
    op.drop_index('ix_providers_company', table_name='providers')
    op.drop_index('ix_providers_description', table_name='providers')
    op.drop_index('ix_providers_name', table_name='providers')
    op.drop_index('ix_providers_provider_id', table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('provider_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('company', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('logo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('creator_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updater_id', mysql.CHAR(length=32), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('provider_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_providers_provider_id', 'providers', ['provider_id'], unique=False)
    op.create_index('ix_providers_name', 'providers', ['name'], unique=False)
    op.create_index('ix_providers_description', 'providers', ['description'], unique=False)
    op.create_index('ix_providers_company', 'providers', ['company'], unique=False)
    op.create_table('store',
    sa.Column('store_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('store_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('creator_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updater_id', mysql.CHAR(length=32), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('store_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_store_user_id', 'store', ['user_id'], unique=False)
    op.create_index('ix_store_store_id', 'store', ['store_id'], unique=False)
    op.create_table('processing',
    sa.Column('processing_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('processing_type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('processing_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('processing_desc', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('template', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('pii_masking', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('normalization', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('stopword_removal', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('creator_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updater_id', mysql.CHAR(length=32), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('processing_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_processing_user_id', 'processing', ['user_id'], unique=False)
    op.create_index('ix_processing_processing_id', 'processing', ['processing_id'], unique=False)
    op.create_table('models',
    sa.Column('model_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('model_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('provider_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('model_type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('creator_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updater_id', mysql.CHAR(length=32), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('model_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_models_provider_id', 'models', ['provider_id'], unique=False)
    op.create_index('ix_models_model_type', 'models', ['model_type'], unique=False)
    op.create_index('ix_models_model_name', 'models', ['model_name'], unique=False)
    op.create_index('ix_models_model_id', 'models', ['model_id'], unique=False)
    op.create_table('agents',
    sa.Column('agent_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('agent_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('agent_description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fm_provider_type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('fm_provider_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('fm_model_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('fm_temperature', mysql.FLOAT(), nullable=False),
    sa.Column('fm_top_p', mysql.FLOAT(), nullable=False),
    sa.Column('fm_request_token_limit', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fm_response_token_limit', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('embedding_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('embedding_provider_id', mysql.CHAR(length=32), nullable=True),
    sa.Column('embedding_model_id', mysql.CHAR(length=32), nullable=True),
    sa.Column('storage_provider_id', mysql.CHAR(length=32), nullable=True),
    sa.Column('storage_object_id', mysql.CHAR(length=32), nullable=True),
    sa.Column('vector_db_provider_id', mysql.CHAR(length=32), nullable=True),
    sa.Column('processing_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('pre_processing_id', mysql.CHAR(length=32), nullable=True),
    sa.Column('post_processing_id', mysql.CHAR(length=32), nullable=True),
    sa.Column('expected_request_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expected_token_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expected_cost', mysql.FLOAT(), nullable=False),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('creator_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updater_id', mysql.CHAR(length=32), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('agent_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_agents_user_id', 'agents', ['user_id'], unique=False)
    op.create_index('ix_agents_fm_provider_id', 'agents', ['fm_provider_id'], unique=False)
    op.create_index('ix_agents_fm_model_id', 'agents', ['fm_model_id'], unique=False)
    op.create_index('ix_agents_agent_id', 'agents', ['agent_id'], unique=False)
    op.create_table('credentials',
    sa.Column('credential_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('provider_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('credential_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('access_key', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('secret_key', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('session_key', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('access_token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('api_key', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('api_endpoint', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('creator_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updater_id', mysql.CHAR(length=32), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('credential_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_credentials_user_id', 'credentials', ['user_id'], unique=False)
    op.create_index('ix_credentials_provider_id', 'credentials', ['provider_id'], unique=False)
    op.create_index('ix_credentials_credential_id', 'credentials', ['credential_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('last_login', mysql.DATETIME(), nullable=False),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('creator_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updater_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_index('ix_user_user_id', 'user', ['user_id'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_table('inquiry',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('inquiry_type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('response_content', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('processing_type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('creator_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updater_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_inquiry_title', 'inquiry', ['title'], unique=False)
    op.create_index('ix_inquiry_inquiry_type', 'inquiry', ['inquiry_type'], unique=False)
    op.create_index('ix_inquiry_id', 'inquiry', ['id'], unique=False)
    op.create_index('ix_inquiry_content', 'inquiry', ['content'], unique=False)
    op.create_table('chain',
    sa.Column('chain_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('connection_order', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('creator_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updater_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('chain_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_chain_chain_id', 'chain', ['chain_id'], unique=False)
    # ### end Alembic commands ###
